/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bil481Proje;

import java.util.ArrayList;

public class App {

   /* public String getGreeting(){
        return "hello world";
    }*/

    public static void main(String[] args){
        int[] narray = new int[5];
        narray[0] = 6;
        narray[1] = 3;
        narray[2] = 9;
        narray[3] = 7;
        narray[4] = 22;
        System.out.println(new App().isBigger(3,4,2,narray));
    }
    /*
    public static boolean search(ArrayList<Integer> array, int e) {
        System.out.println("inside search");
        if (array == null) return false;
  
        for (int elt : array) {
          if (elt == e) return true;
        }
        return false;
      }*/




    public static boolean isBigger(int num1, int num2, int num3, int[] arr){
        // if array has num1, num2 and sum of these numbers are bigger than num3 return true, if not false
        boolean num1v = false;
        boolean num2v = false;
        for(int i=0; i<arr.length; i++){
            if(arr[i] == num1){
                num1v = true;    
            }
            if(arr[i] == num2){
                num2v = true;
            }
        }
        if(num1v == true && num2v == true){
            if(num1+num2 > num3){
                return true;
            }
            else
                return false;
        }
        return false;
    }
/*
    public static void main(String[] args) {
        int[] arr = new int[5];
        arr[0] = 6;
        arr[1] = 3;
        arr[2] = 9;
        arr[3] = 7;
        arr[4] = 22;
        System.out.println(new App().isBigger(3,6,2,arr));
    }*/
}
